# Tieteellinen tieto, tilastot ja arkitieto yhteiskunnassa {#luku2}

## Mit채 on tiede? {#alaluku21}

## Tieteellinen menetelm채 {#alaluku22}

## Tilastojen yleisest채 roolista yhteiskunnassa {#alaluku23}

## Mit채 on tutkimus? {#alaluku24}

## Tieteellisen tutkimuksen vaiheet ja tulosten julkaiseminen {#alaluku25}

```{r nice-fig, fig.cap='Here is a nice figure!', out.width='80%', fig.asp=.75, fig.align='center', include=FALSE}
par(mar = c(4, 4, .1, .1))
plot(pressure, type = 'b', pch = 19)
#Reference a figure by its code chunk label with the `fig:` prefix, e.g., see Figure \@ref(fig:nice-fig).
```

```{r nice-tab, tidy=FALSE, include = FALSE}
knitr::kable(
  head(iris, 20), caption = 'Here is a nice table!',
  booktabs = TRUE
)
# you can reference tables generated from `knitr::kable()`, e.g., see Table \@ref(tab:nice-tab).
```

```{r sitaatit, include = FALSE}
#You can write citations, too. For example, we are using the **bookdown** package [@R-bookdown] in this sample book, which was built on top of R Markdown and **knitr** [@xie2015].
```

