---
title: "Tiivistelmiä"
author: "Roope Rihtamo"
date: "2023-08-09"
output: html_document
---

# Luku 2 

## 2.1

"Huge if true" - eli tieteellinen tieto varmentuu vasta monien mittausten aikana.

## 2.2

Tieteellinen menetelmä ja sen kriteerit
Replikointi

## 2.3

Tilastot (ja tilastotiede/menetelmät) ovat demokratian ja yhteiskunnassa toimimisen edellytys

## 2.4


Along these lines, Caruana et al. (2015) describe a model trained to predict probability of death from
pneumonia that assigned less risk to patients if they also
had asthma. In fact, asthma was predictive of lower risk of
death. This owed to the more aggressive treatment these
patients received. But if the model were deployed to aid
in triage, these patients would then receive less aggressive
treatment, invalidating the model.

Statistics is the most important science in the whole world: for upon it depends the practical application of every other science and of every art: the one science essential to all political and social administration, all education, all organization based on experience, for it only gives results of our experience.
~Florence Nightingale